"""add_billing_to_org

Revision ID: 1e02c0d2a897
Revises: 0271ad04db04
Create Date: 2026-09-29 10:09:11.748980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e02c0d2a897'
down_revision: Union[str, Sequence[str], None] = '0271ad04db04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('plan_id', sa.String(length=50), nullable=False))
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'organizations', ['stripe_subscription_id'])
    op.create_unique_constraint(None, 'organizations', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'organizations', type_='unique')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'plan_id')
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###
