"""Add API scopes and request logs

Revision ID: 390366244e37
Revises: 5c545352c729
Create Date: 2026-09-29 21:42:02.385107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390366244e37'
down_revision: Union[str, Sequence[str], None] = '5c545352c729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('api_key_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_logs_api_key_id'), 'api_request_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_endpoint'), 'api_request_logs', ['endpoint'], unique=False)
    op.add_column('api_keys', sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'scopes')
    op.drop_index(op.f('ix_api_request_logs_endpoint'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_api_key_id'), table_name='api_request_logs')
    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
